# config/meta.yml
meta_title: "Hello there! Look, this is my movie collection on Mustachio"
meta_description: "Go check it out and build yours!"
meta_image: "logo-meta.png" # Une image dans votre dossier app/assets/images/
